// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/tools/list-pipelines.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireUser(ctx) {
  const userId = ctx.getUserId();
  if (!ctx.isAuthenticated() || !userId) throw new Error("Not authenticated");
  return userId;
}

// src/lib/mcp/tools/list-pipelines.ts
var list_pipelines_default = defineTool({
  name: "list_pipelines",
  title: "List pipelines",
  description: "List the caller's sales pipelines with their stages in order.",
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("pipelines").select("id, name, pipeline_stages(id, name, position)").order("created_at", { ascending: true });
    if (error) throw new ToolError(error.message);
    const pipelines = (data ?? []).map((p) => ({
      id: p.id,
      name: p.name,
      stages: [...p.pipeline_stages ?? []].sort((a, b) => a.position - b.position).map((s) => ({ id: s.id, name: s.name, position: s.position }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(pipelines) }],
      structuredContent: { pipelines }
    };
  }
});

// src/lib/mcp/tools/list-deals.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z } from "npm:zod@^3.25.76";
var one = (value) => Array.isArray(value) ? value[0] ?? null : value ?? null;
var list_deals_default = defineTool2({
  name: "list_deals",
  title: "List deals",
  description: "List the caller's deals, optionally filtered by pipeline or stage.",
  inputSchema: {
    pipeline_id: z.string().uuid().optional().describe("Only deals in this pipeline."),
    stage_id: z.string().uuid().optional().describe("Only deals in this stage."),
    limit: z.number().int().min(1).max(200).default(50).describe("Maximum deals to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pipeline_id, stage_id, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("deals").select(
      "id, title, value, probability, close_date, notes, pipeline_id, stage_id, pipeline_stages(name), companies(name), contacts(first_name, last_name)"
    ).order("updated_at", { ascending: false }).limit(limit);
    if (pipeline_id) query = query.eq("pipeline_id", pipeline_id);
    if (stage_id) query = query.eq("stage_id", stage_id);
    const { data, error } = await query;
    if (error) throw new ToolError2(error.message);
    const deals = (data ?? []).map((d) => ({
      id: d.id,
      title: d.title,
      value: d.value,
      probability: d.probability,
      close_date: d.close_date,
      notes: d.notes,
      pipeline_id: d.pipeline_id,
      stage_id: d.stage_id,
      stage: one(d.pipeline_stages)?.name ?? null,
      company: one(d.companies)?.name ?? null,
      contact: one(d.contacts) ? `${one(d.contacts).first_name} ${one(d.contacts).last_name}` : null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(deals) }],
      structuredContent: { deals }
    };
  }
});

// src/lib/mcp/tools/create-deal.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_deal_default = defineTool3({
  name: "create_deal",
  title: "Create deal",
  description: "Create a new deal in one of the caller's pipeline stages.",
  inputSchema: {
    title: z2.string().trim().min(1).max(200).describe("Deal title."),
    pipeline_id: z2.string().uuid().describe("Pipeline the deal belongs to."),
    stage_id: z2.string().uuid().describe("Stage within that pipeline."),
    value: z2.number().nonnegative().optional().describe("Deal value in the account currency."),
    probability: z2.number().int().min(0).max(100).optional().describe("Win probability percentage."),
    close_date: z2.string().date().optional().describe("Expected close date (YYYY-MM-DD)."),
    company_id: z2.string().uuid().optional().describe("Related company."),
    contact_id: z2.string().uuid().optional().describe("Primary contact."),
    notes: z2.string().max(2e3).optional().describe("Free-form notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (args, ctx) => {
    const userId = requireUser(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("deals").insert({ ...args, owner_id: userId, created_by: userId }).select("id, title, value, stage_id, pipeline_id").single();
    if (error) throw new ToolError3(error.message);
    const deal = {
      id: data.id,
      title: data.title,
      value: data.value,
      stage_id: data.stage_id,
      pipeline_id: data.pipeline_id
    };
    return {
      content: [{ type: "text", text: `Created deal "${deal.title}".` }],
      structuredContent: { deal }
    };
  }
});

// src/lib/mcp/tools/update-deal.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z3 } from "npm:zod@^3.25.76";
var update_deal_default = defineTool4({
  name: "update_deal",
  title: "Update deal",
  description: "Update a deal's stage, value, probability, close date, or notes.",
  inputSchema: {
    deal_id: z3.string().uuid().describe("Deal to update."),
    stage_id: z3.string().uuid().optional().describe("Move the deal to this stage."),
    title: z3.string().trim().min(1).max(200).optional(),
    value: z3.number().nonnegative().optional(),
    probability: z3.number().int().min(0).max(100).optional(),
    close_date: z3.string().date().optional(),
    notes: z3.string().max(2e3).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ deal_id, ...patch }, ctx) => {
    const updates = Object.fromEntries(Object.entries(patch).filter(([, v]) => v !== void 0));
    if (Object.keys(updates).length === 0) throw new ToolError4("Provide at least one field to update.");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("deals").update(updates).eq("id", deal_id).select("id, title, value, probability, close_date, stage_id").maybeSingle();
    if (error) throw new ToolError4(error.message);
    if (!data) throw new ToolError4("Deal not found.");
    const deal = {
      id: data.id,
      title: data.title,
      value: data.value,
      probability: data.probability,
      close_date: data.close_date,
      stage_id: data.stage_id
    };
    return {
      content: [{ type: "text", text: `Updated deal "${deal.title}".` }],
      structuredContent: { deal }
    };
  }
});

// src/lib/mcp/tools/list-contacts.ts
import { defineTool as defineTool5, ToolError as ToolError5 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z4 } from "npm:zod@^3.25.76";
var one2 = (value) => Array.isArray(value) ? value[0] ?? null : value ?? null;
var list_contacts_default = defineTool5({
  name: "list_contacts",
  title: "List contacts",
  description: "List or search the caller's contacts by name or email.",
  inputSchema: {
    search: z4.string().trim().min(1).max(100).optional().describe("Match against first name, last name, or email."),
    limit: z4.number().int().min(1).max(200).default(50).describe("Maximum contacts to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("contacts").select("id, first_name, last_name, email, phone, position, company_id, companies(name)").order("created_at", { ascending: false }).limit(limit);
    if (search) {
      const term = search.replace(/[%,]/g, "");
      query = query.or(
        `first_name.ilike.%${term}%,last_name.ilike.%${term}%,email.ilike.%${term}%`
      );
    }
    const { data, error } = await query;
    if (error) throw new ToolError5(error.message);
    const contacts = (data ?? []).map((c) => ({
      id: c.id,
      first_name: c.first_name,
      last_name: c.last_name,
      email: c.email,
      phone: c.phone,
      position: c.position,
      company_id: c.company_id,
      company: one2(c.companies)?.name ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(contacts) }],
      structuredContent: { contacts }
    };
  }
});

// src/lib/mcp/tools/create-contact.ts
import { defineTool as defineTool6, ToolError as ToolError6 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z5 } from "npm:zod@^3.25.76";
var create_contact_default = defineTool6({
  name: "create_contact",
  title: "Create contact",
  description: "Add a new contact to the caller's CRM.",
  inputSchema: {
    first_name: z5.string().trim().min(1).max(100),
    last_name: z5.string().trim().min(1).max(100),
    email: z5.string().trim().email().max(255).optional(),
    phone: z5.string().trim().max(50).optional(),
    position: z5.string().trim().max(120).optional(),
    company_id: z5.string().uuid().optional().describe("Company this contact works for.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (args, ctx) => {
    const userId = requireUser(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("contacts").insert({ ...args, created_by: userId }).select("id, first_name, last_name, email").single();
    if (error) throw new ToolError6(error.message);
    const contact = {
      id: data.id,
      first_name: data.first_name,
      last_name: data.last_name,
      email: data.email
    };
    return {
      content: [{ type: "text", text: `Created contact ${contact.first_name} ${contact.last_name}.` }],
      structuredContent: { contact }
    };
  }
});

// src/lib/mcp/tools/list-companies.ts
import { defineTool as defineTool7, ToolError as ToolError7 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_companies_default = defineTool7({
  name: "list_companies",
  title: "List companies",
  description: "List or search the caller's companies by name.",
  inputSchema: {
    search: z6.string().trim().min(1).max(100).optional().describe("Match against the company name."),
    limit: z6.number().int().min(1).max(200).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("companies").select("id, name, industry, website").order("name", { ascending: true }).limit(limit);
    if (search) query = query.ilike("name", `%${search.replace(/[%,]/g, "")}%`);
    const { data, error } = await query;
    if (error) throw new ToolError7(error.message);
    const companies = (data ?? []).map((c) => ({
      id: c.id,
      name: c.name,
      industry: c.industry,
      website: c.website
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(companies) }],
      structuredContent: { companies }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { defineTool as defineTool8, ToolError as ToolError8 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z7 } from "npm:zod@^3.25.76";
var create_task_default = defineTool8({
  name: "create_task",
  title: "Create task",
  description: "Create a follow-up task for the caller, optionally linked to a deal or contact.",
  inputSchema: {
    title: z7.string().trim().min(1).max(200),
    description: z7.string().max(2e3).optional(),
    due_date: z7.string().date().optional().describe("Due date (YYYY-MM-DD)."),
    priority: z7.enum(["low", "medium", "high"]).default("medium"),
    deal_id: z7.string().uuid().optional(),
    contact_id: z7.string().uuid().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (args, ctx) => {
    const userId = requireUser(ctx);
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("tasks").insert({ ...args, user_id: userId }).select("id, title, due_date, priority, completed").single();
    if (error) throw new ToolError8(error.message);
    const task = {
      id: data.id,
      title: data.title,
      due_date: data.due_date,
      priority: data.priority,
      completed: data.completed
    };
    return {
      content: [{ type: "text", text: `Created task "${task.title}".` }],
      structuredContent: { task }
    };
  }
});

// src/lib/mcp/tools/pipeline-summary.ts
import { defineTool as defineTool9, ToolError as ToolError9 } from "npm:@lovable.dev/mcp-js@3.0.1";
import { z as z8 } from "npm:zod@^3.25.76";
var pipeline_summary_default = defineTool9({
  name: "pipeline_summary",
  title: "Pipeline summary",
  description: "Summarize deal count and total value per stage for a pipeline.",
  inputSchema: {
    pipeline_id: z8.string().uuid().optional().describe("Pipeline to summarize; defaults to the first pipeline.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ pipeline_id }, ctx) => {
    const supabase = supabaseForUser(ctx);
    let targetPipelineId = pipeline_id;
    if (!targetPipelineId) {
      const { data, error } = await supabase.from("pipelines").select("id").order("created_at", { ascending: true }).limit(1).maybeSingle();
      if (error) throw new ToolError9(error.message);
      if (!data) throw new ToolError9("No pipeline found for this account.");
      targetPipelineId = data.id;
    }
    const [stagesResult, dealsResult] = await Promise.all([
      supabase.from("pipeline_stages").select("id, name, position").eq("pipeline_id", targetPipelineId).order("position", { ascending: true }),
      supabase.from("deals").select("stage_id, value").eq("pipeline_id", targetPipelineId)
    ]);
    if (stagesResult.error) throw new ToolError9(stagesResult.error.message);
    if (dealsResult.error) throw new ToolError9(dealsResult.error.message);
    const deals = dealsResult.data ?? [];
    const stages = (stagesResult.data ?? []).map((stage) => {
      const stageDeals = deals.filter((d) => d.stage_id === stage.id);
      return {
        id: stage.id,
        name: stage.name,
        position: stage.position,
        deal_count: stageDeals.length,
        total_value: stageDeals.reduce((sum, d) => sum + (d.value ?? 0), 0)
      };
    });
    const summary = {
      pipeline_id: targetPipelineId,
      total_deals: deals.length,
      total_value: deals.reduce((sum, d) => sum + (d.value ?? 0), 0),
      stages
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: { summary }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "drwzefybkwrjovuqmjql";
var mcp_default = defineMcp({
  name: "fafo-boa-sales-pipeline-crm",
  title: "FAFO-BOA Sales Pipeline CRM",
  version: "0.1.0",
  instructions: "Tools for the FAFO-BOA Sales Pipeline CRM. Call `list_pipelines` first to get pipeline and stage IDs, then use `list_deals`, `create_deal`, and `update_deal` to manage the signed-in user's pipeline. `list_contacts`, `create_contact`, and `list_companies` manage people and accounts, `create_task` adds follow-ups, and `pipeline_summary` reports deal count and value per stage. All tools act as the signed-in CRM user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_pipelines_default,
    list_deals_default,
    create_deal_default,
    update_deal_default,
    list_contacts_default,
    create_contact_default,
    list_companies_default,
    create_task_default,
    pipeline_summary_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
